# -*- coding: utf-8 -*-
"""Proyecto Optimización

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iC-1iOaQB6e6srnzzjtWMU_NBh4lv68s
"""
# =====================================================
# GEMELO DIGITAL – GASODUCTO TRANsANDINO 
# Optimización de Procesos 
=======================================================
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from itertools import product

# =============================================================================
# CONFIGURACIÓN DE LA PÁGINA
# =============================================================================
st.set_page_config(
    page_title="Gemelo Digital – Gasoducto Trans-Andino",
    page_icon="⛽",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =============================================================================
# BASE DE DATOS TÉCNICA (Tablas del enunciado)
# =============================================================================
datos_tuberia = pd.DataFrame([
    {"DN_pulg": 12, "DE_mm": 323.8, "espesor_mm": 10.31, "costo_USD_m": 185},
    {"DN_pulg": 16, "DE_mm": 406.4, "espesor_mm": 12.70, "costo_USD_m": 260},
    {"DN_pulg": 20, "DE_mm": 508.0, "espesor_mm": 15.09, "costo_USD_m": 350},
    {"DN_pulg": 24, "DE_mm": 609.6, "espesor_mm": 17.48, "costo_USD_m": 440},
])

datos_acero = pd.DataFrame([
    {"grado": "X52", "SMYS_psi": 52000, "F": 0.72},
    {"grado": "X60", "SMYS_psi": 60000, "F": 0.72},
])

# =============================================================================
# PARÁMETROS FIJOS DEL PROCESO
# =============================================================================
longitud_total_km = 400.0
presion_entrada_psia = 800.0
presion_entrega_min_psia = 500.0
caudal_base_MMscfd = 500.0
gravedad_especifica = 0.65
factor_compresibilidad = 0.90
temp_succion_K = 293.15      # 20°C
R_universal = 10.7316        # psia·ft³/(lbmol·°R)
pies_por_km = 3280.84

# =============================================================================
# FUNCIONES DEL MODELO MATEMÁTICO (CORREGIDAS)
# =============================================================================

def weymouth_dp(caudal_MMscfd, longitud_km, diametro_pulg, gravedad, temp_K, Z):
    """
    Ecuación de Weymouth para caída de presión al cuadrado.
    Retorna delta(P^2) = P1² - P2² [psia²].
    Basado en la fórmula estándar de la literatura de gasoductos.
    """
    T_R = temp_K * 9.0/5.0                     # Rankine
    L_pies = longitud_km * pies_por_km         # pies
    D_pulg = float(diametro_pulg)
    # Constante de Weymouth (para Q en MMscfd, L en pies, D en pulg)
    C = 433.5
    # Fórmula correcta: dp2 = (Q^2 * L * gamma * T * Z) / (C^2 * D^(16/3))
    dp2 = (caudal_MMscfd**2 * gravedad * T_R * Z * L_pies) / (C**2 * D_pulg**(16/3))
    return dp2

def presion_despues_friccion(P1_psia, dp2):
    """Calcula P2 después de una caída de presión conocida (P1² - P2² = dp2)."""
    if P1_psia**2 - dp2 <= 0:
        return 0.0
    return np.sqrt(P1_psia**2 - dp2)

def presion_descarga_necesaria(P_objetivo_psia, dp2):
    """Dada la presión al final de un tramo, calcula la presión necesaria al inicio."""
    return np.sqrt(P_objetivo_psia**2 + dp2)

def potencia_compresor(caudal_MMscfd, P_entrada_psia, P_salida_psia, T_entrada_K, gravedad, Z, eficiencia=0.85):
    """Potencia de compresión (HP) para una estación."""
    T_entrada_R = T_entrada_K * 9.0/5.0
    k = 1.27
    flujo_scfs = caudal_MMscfd * 1e6 / (24 * 3600)
    term1 = flujo_scfs * Z * R_universal * T_entrada_R / (550 * eficiencia)
    term2 = (k/(k-1)) * ((P_salida_psia / P_entrada_psia)**((k-1)/k) - 1)
    hp = term1 * term2
    return max(0.0, hp)

def temperatura_descarga(T_entrada_K, P_entrada_psia, P_salida_psia):
    """Temperatura de descarga de una estación (K)."""
    k = 1.27
    relacion = (P_salida_psia / P_entrada_psia)**((k-1)/k)
    T_salida_K = T_entrada_K * relacion
    return T_salida_K

def maop_barlow(diametro_pulg, espesor_mm, SMYS_psi, F):
    """Presión máxima admisible según Barlow (MAOP) en psia."""
    espesor_pulg = espesor_mm / 25.4
    if diametro_pulg <= 0 or espesor_pulg <= 0:
        return 0.0
    MAOP = (2 * SMYS_psi * F * espesor_pulg) / diametro_pulg
    return MAOP

# =============================================================================
# FUNCIONES DE COSTOS
# =============================================================================

def factor_recuperacion_capital(tasa_interes, años=20):
    i = tasa_interes / 100.0
    if i == 0:
        return 1.0 / años
    return i * (1+i)**años / ((1+i)**años - 1)

def calcular_tac(capex_tuberia, capex_compresores, opex_energia, tasa_interes, años=20):
    crf = factor_recuperacion_capital(tasa_interes, años)
    tac = (capex_tuberia + capex_compresores) * crf + opex_energia
    return tac

# =============================================================================
# SIMULACIÓN PRINCIPAL (CORREGIDA)
# =============================================================================

def simular_configuracion(dn_pulg, grado_acero, caudal_MMscfd, num_estaciones,
                          costo_energia_USD_kWh, costo_compresor_USD_HP,
                          tasa_interes_pct, años=20):
    """
    Ejecuta todos los cálculos para una combinación de parámetros.
    Retorna un diccionario con resultados y banderas de alerta.
    """
    # Obtener datos de tubería y acero
    fila_tubo = datos_tuberia[datos_tuberia["DN_pulg"] == dn_pulg].iloc[0]
    DE_mm = fila_tubo["DE_mm"]
    espesor_mm = fila_tubo["espesor_mm"]
    costo_tuberia_m = fila_tubo["costo_USD_m"]
    fila_acero = datos_acero[datos_acero["grado"] == grado_acero].iloc[0]
    SMYS = fila_acero["SMYS_psi"]
    F_diseno = fila_acero["F"]
    
    # Diámetro interno (para hidráulica)
    diametro_int_pulg = (DE_mm - 2*espesor_mm) / 25.4
    if diametro_int_pulg <= 0:
        diametro_int_pulg = DE_mm / 25.4
    
    # Longitud por tramo
    longitud_tramo_km = longitud_total_km / num_estaciones
    
    # Caída de presión en un tramo (dp2)
    dp2_tramo = weymouth_dp(caudal_MMscfd, longitud_tramo_km, diametro_int_pulg,
                            gravedad_especifica, temp_succion_K, factor_compresibilidad)
    
    # --- Cálculo de presiones nodo desde el final hacia atrás ---
    presiones_nodo = [0.0] * (num_estaciones + 1)
    presiones_nodo[-1] = presion_entrega_min_psia   # presión al final del último tramo
    
    for i in range(num_estaciones-1, -1, -1):
        pres_necesaria = presion_descarga_necesaria(presiones_nodo[i+1], dp2_tramo)
        presiones_nodo[i] = pres_necesaria
    
    # Ajuste: la primera estación no puede entregar menos que la presión de entrada
    # (si la presión calculada es menor, significa que no se necesita compresión ahí)
    if presiones_nodo[0] < presion_entrada_psia:
        presiones_nodo[0] = presion_entrada_psia
        # Recalcular las siguientes hacia adelante para mantener consistencia
        for i in range(num_estaciones):
            if i == 0:
                continue
            # La presión al inicio del tramo i es la presión de descarga de la estación i-1
            # pero después de la caída obtenemos la succión de la estación i
            P_inicio_tramo = presiones_nodo[i-1]
            P_fin_tramo = presion_despues_friccion(P_inicio_tramo, dp2_tramo)
            # La presión de succión de la estación i es P_fin_tramo
            # La presión de descarga necesaria para la estación i se recalcula:
            presiones_nodo[i] = presion_descarga_necesaria(presiones_nodo[i+1], dp2_tramo)
            # Pero si la presión de descarga calculada es menor que la succión, la estación no comprime
            if presiones_nodo[i] < P_fin_tramo:
                presiones_nodo[i] = P_fin_tramo
    
    # Ahora obtener presiones de succión y descarga por estación
    P_succion = [0.0] * num_estaciones
    P_descarga = [0.0] * num_estaciones
    P_descarga[0] = presiones_nodo[0]
    P_succion[0] = presion_entrada_psia   # la primera estación recibe la presión de entrada
    
    for i in range(1, num_estaciones):
        # La presión de succión de la estación i es la presión al final del tramo i-1
        P_succion[i] = presion_despues_friccion(P_descarga[i-1], dp2_tramo)
        P_descarga[i] = presiones_nodo[i]
    
    # Calcular potencia y temperatura de salida para cada estación
    hp_estacion = []
    temp_salida_K_estacion = []
    for i in range(num_estaciones):
        # Solo si la relación de compresión es mayor que 1 (realmente comprime)
        if P_descarga[i] > P_succion[i]:
            hp = potencia_compresor(caudal_MMscfd, P_succion[i], P_descarga[i], temp_succion_K,
                                    gravedad_especifica, factor_compresibilidad)
            T_out_K = temperatura_descarga(temp_succion_K, P_succion[i], P_descarga[i])
        else:
            hp = 0.0
            T_out_K = temp_succion_K
        hp_estacion.append(hp)
        temp_salida_K_estacion.append(T_out_K)
    
    hp_total = sum(hp_estacion)
    temp_max_K = max(temp_salida_K_estacion) if temp_salida_K_estacion else temp_succion_K
    temp_max_C = temp_max_K - 273.15
    
    # Presión final real (después del último tramo)
    P_final_real = presion_despues_friccion(P_descarga[-1], dp2_tramo)
    
    # MAOP
    MAOP = maop_barlow(diametro_int_pulg, espesor_mm, SMYS, F_diseno)
    # Presión máxima que ve el sistema (la mayor entre descargas y entrada)
    P_max_sistema = max(P_descarga + [presion_entrada_psia])
    
    # Alertas
    alerta_maop = P_max_sistema > MAOP
    alerta_temp = temp_max_C > 65.0
    alerta_presion = P_final_real < presion_entrega_min_psia
    
    # Costos
    capex_tuberia = costo_tuberia_m * longitud_total_km * 1000.0
    capex_compresores = costo_compresor_USD_HP * hp_total
    horas_anio = 8760
    consumo_kW = hp_total * 0.7457
    opex_energia = consumo_kW * horas_anio * costo_energia_USD_kWh
    TAC = calcular_tac(capex_tuberia, capex_compresores, opex_energia, tasa_interes_pct, años)
    
    resultados = {
        "TAC_USD": TAC,
        "HP_total": hp_total,
        "P_final_psia": P_final_real,
        "P_max_psia": P_max_sistema,
        "MAOP_psia": MAOP,
        "T_max_C": temp_max_C,
        "alerta_maop": alerta_maop,
        "alerta_temp": alerta_temp,
        "alerta_presion": alerta_presion,
        "capex_tuberia": capex_tuberia,
        "capex_compresores": capex_compresores,
        "opex_energia": opex_energia,
        "P_succion": P_succion,
        "P_descarga": P_descarga,
        "dp2_tramo": dp2_tramo,
        "diametro_int_pulg": diametro_int_pulg,
        "HP_estacion": hp_estacion,
        "T_salida_estacion_C": [t-273.15 for t in temp_salida_K_estacion],
        "presiones_nodo": presiones_nodo,
    }
    return resultados

# =============================================================================
# GRÁFICO DEL PERFIL HIDRÁULICO
# =============================================================================

def graficar_perfil_hidraulico(resultados, num_estaciones, longitud_total_km, caudal_MMscfd, dn_pulg):
    P_descarga = resultados["P_descarga"]
    dp2_tramo = resultados["dp2_tramo"]
    longitud_tramo_km = longitud_total_km / num_estaciones
    
    distancias = []
    presiones = []
    
    for i in range(num_estaciones):
        x_inicio = i * longitud_tramo_km
        x_fin = (i+1) * longitud_tramo_km
        P_inicio_tramo = P_descarga[i]
        n_puntos = 50
        for j in range(n_puntos):
            frac = j / (n_puntos - 1)
            x = x_inicio + frac * longitud_tramo_km
            P2 = max(0, P_inicio_tramo**2 - frac * dp2_tramo)
            P = np.sqrt(P2)
            distancias.append(x)
            presiones.append(P)
        if i < num_estaciones - 1:
            P_fin_tramo = presion_despues_friccion(P_inicio_tramo, dp2_tramo)
            distancias.append(x_fin)
            presiones.append(P_fin_tramo)
            distancias.append(x_fin)
            presiones.append(P_descarga[i+1])
    
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=distancias, y=presiones, mode='lines', name='Presión',
                             line=dict(color='#0068c9', width=3)))
    x_estaciones = [i * longitud_tramo_km for i in range(num_estaciones)]
    fig.add_trace(go.Scatter(x=x_estaciones, y=P_descarga, mode='markers',
                             marker=dict(color='red', size=10, symbol='triangle-down'),
                             name='Estación de compresión (descarga)'))
    fig.add_hline(y=presion_entrega_min_psia, line_dash="dash", line_color="orange",
                  annotation_text=f"P entrega mín = {presion_entrega_min_psia} psia")
    MAOP = resultados["MAOP_psia"]
    if MAOP > 0:
        fig.add_hline(y=MAOP, line_dash="dash", line_color="red",
                      annotation_text=f"MAOP = {MAOP:.0f} psia")
    fig.update_layout(
        title=f"Perfil Hidráulico – Q = {caudal_MMscfd:.0f} MMscfd, Diámetro {dn_pulg}\"",
        xaxis_title="Distancia (km)",
        yaxis_title="Presión (psia)",
        hovermode="x unified",
        template="plotly_dark",
        height=500
    )
    return fig

# =============================================================================
# OPTIMIZACIÓN AUTOMÁTICA
# =============================================================================

def optimizar_configuracion(parametros_economicos):
    mejor = None
    mejor_tac = float('inf')
    diametros = datos_tuberia["DN_pulg"].tolist()
    grados = datos_acero["grado"].tolist()
    rango_N = range(1, 6)
    for dn, grado, N in product(diametros, grados, rango_N):
        try:
            sim = simular_configuracion(
                dn, grado, caudal_base_MMscfd, N,
                parametros_economicos["costo_energia"],
                parametros_economicos["costo_compresor"],
                parametros_economicos["tasa_interes"]
            )
            if not (sim["alerta_maop"] or sim["alerta_temp"] or sim["alerta_presion"]):
                if sim["TAC_USD"] < mejor_tac:
                    mejor_tac = sim["TAC_USD"]
                    mejor = {
                        "DN_pulg": dn,
                        "grado": grado,
                        "N_estaciones": N,
                        "TAC_USD": sim["TAC_USD"],
                        "HP_total": sim["HP_total"],
                        "P_final": sim["P_final_psia"],
                        "MAOP": sim["MAOP_psia"],
                        "T_max_C": sim["T_max_C"]
                    }
        except Exception:
            continue
    return mejor

# =============================================================================
# INTERFAZ PRINCIPAL
# =============================================================================

def main():
    st.title("⛽ Gemelo Digital – Gasoducto Trans‑Andino")
    st.markdown("""
    Optimización del transporte de gas natural. Ajuste los parámetros en el panel lateral
    y observe el impacto en el costo total anualizado (TAC), el perfil de presión y las alertas de seguridad.
    """)
    
    with st.sidebar:
        st.header("⚙️ Parámetros económicos")
        costo_energia = st.number_input("Costo de energía (USD/kWh)", min_value=0.01, max_value=0.50, value=0.05, step=0.01, format="%.3f")
        costo_compresor = st.number_input("Costo de compresor (USD/HP)", min_value=100, max_value=2000, value=800, step=50)
        tasa_interes = st.number_input("Tasa de interés anual (%)", min_value=0.0, max_value=20.0, value=8.0, step=0.5)
        
        st.header("📏 Selección de materiales")
        dn_seleccionado = st.selectbox("Diámetro nominal (pulg)", datos_tuberia["DN_pulg"].tolist())
        grado_seleccionado = st.selectbox("Grado del acero", datos_acero["grado"].tolist())
        
        st.header("🔧 Variables operativas")
        Q_usuario = st.number_input("Flujo de gas (MMscfd)", min_value=100.0, max_value=1500.0, value=500.0, step=10.0)
        num_estaciones = st.slider("Número de estaciones de compresión", min_value=1, max_value=6, value=2, step=1)
        
        if st.button("🚀 Optimizar automáticamente", type="primary"):
            with st.spinner("Buscando la configuración óptima..."):
                economicos = {
                    "costo_energia": costo_energia,
                    "costo_compresor": costo_compresor,
                    "tasa_interes": tasa_interes
                }
                mejor = optimizar_configuracion(economicos)
                if mejor:
                    st.session_state["optimo"] = mejor
                    st.success(f"Óptimo: {mejor['DN_pulg']}\", {mejor['grado']}, {mejor['N_estaciones']} estaciones → TAC = {mejor['TAC_USD']:,.0f} USD/año")
                else:
                    st.error("No se encontró configuración viable. Ajuste los parámetros.")
    
    # Simulación actual
    resultados = simular_configuracion(
        dn_seleccionado, grado_seleccionado, Q_usuario, num_estaciones,
        costo_energia, costo_compresor, tasa_interes
    )
    
    col1, col2, col3 = st.columns(3)
    col1.metric("💰 TAC (USD/año)", f"{resultados['TAC_USD']:,.0f}")
    col2.metric("⚡ Potencia total (HP)", f"{resultados['HP_total']:.0f}")
    col3.metric("📉 Presión final (psia)", f"{resultados['P_final_psia']:.1f}", 
                delta=f"Objetivo: {presion_entrega_min_psia} psia", 
                delta_color="inverse" if resultados['P_final_psia'] < presion_entrega_min_psia else "normal")
    
    a1, a2, a3 = st.columns(3)
    with a1:
        if resultados["alerta_maop"]:
            st.error(f"⚠️ MAOP: {resultados['P_max_psia']:.0f} psia > {resultados['MAOP_psia']:.0f} psia")
        else:
            st.success(f"✅ MAOP: {resultados['P_max_psia']:.0f} ≤ {resultados['MAOP_psia']:.0f} psia")
    with a2:
        if resultados["alerta_temp"]:
            st.error(f"⚠️ Temperatura: {resultados['T_max_C']:.1f} °C > 65 °C")
        else:
            st.success(f"✅ Temperatura: {resultados['T_max_C']:.1f} °C")
    with a3:
        if resultados["alerta_presion"]:
            st.error(f"⚠️ Presión entrega: {resultados['P_final_psia']:.1f} < {presion_entrega_min_psia} psia")
        else:
            st.success(f"✅ Presión entrega: {resultados['P_final_psia']:.1f} psia")
    
    st.subheader("📊 Perfil de presión")
    fig = graficar_perfil_hidraulico(resultados, num_estaciones, longitud_total_km, Q_usuario, dn_seleccionado)
    st.plotly_chart(fig, use_container_width=True)
    
    st.subheader("💰 Desglose de costos anualizados")
    crf = factor_recuperacion_capital(tasa_interes)
    df_costos = pd.DataFrame({
        "Concepto": ["CAPEX (Tubería)", "CAPEX (Compresores)", "OPEX (Energía)"],
        "Costo Anual (USD)": [
            resultados["capex_tuberia"] * crf,
            resultados["capex_compresores"] * crf,
            resultados["opex_energia"]
        ]
    })
    fig_pie = px.pie(df_costos, values="Costo Anual (USD)", names="Concepto",
                     title="Distribución del costo anualizado",
                     color_discrete_sequence=px.colors.sequential.Blues_r)
    st.plotly_chart(fig_pie, use_container_width=True)
    
    with st.expander("🔍 Detalles por estación"):
        df_est = pd.DataFrame({
            "Estación": [f"#{i+1}" for i in range(num_estaciones)],
            "P_succión (psia)": [f"{p:.1f}" for p in resultados["P_succion"]],
            "P_descarga (psia)": [f"{p:.1f}" for p in resultados["P_descarga"]],
            "Potencia (HP)": [f"{hp:.0f}" for hp in resultados["HP_estacion"]],
            "T_salida (°C)": [f"{t:.1f}" for t in resultados["T_salida_estacion_C"]]
        })
        st.dataframe(df_est, use_container_width=True)
    
    if "optimo" in st.session_state:
        st.success("### 🎯 Configuración óptima encontrada")
        opt = st.session_state["optimo"]
        st.write(f"**Diámetro:** {opt['DN_pulg']}″ — **Grado:** {opt['grado']} — **Estaciones:** {opt['N_estaciones']}")
        st.write(f"**TAC mínimo:** {opt['TAC_USD']:,.0f} USD/año")
        st.write(f"**Potencia:** {opt['HP_total']:.0f} HP | **P_final:** {opt['P_final']:.1f} psia | **MAOP:** {opt['MAOP']:.0f} psia | **T_max:** {opt['T_max_C']:.1f} °C")
        if st.button("Limpiar óptimo"):
            del st.session_state["optimo"]
            st.rerun()

if __name__ == "__main__":
    main()
